const en = {
  languageEnglish: "English",
  languageMarathi: "मराठी",
  switchLanguage: "Switch Language",
  moreTab: "More",
  settingsTitle: "Settings",
  languageLabel: "Language",
  themeLabel: "Theme",
  themeSystem: "System Default",
  themeLight: "Light",
  themeDark: "Dark",
  aboutProject: "About Project Pankaj",
  aboutProjectDescription:
    "This salon dashboard helps you manage transactions, workers, services, expenses and reports from a single app.",
  developerInfo: "Developer Information",
  developerName: "Developed by Pankaj",
  developerContact: "hello@pankajhairsalon.app",

  homeTab: "Home",
  exploreTab: "Explore",
  modalTitle: "Modal",
  modalMessage: "This is a modal",
  goToHomeScreen: "Go to home screen",

  salonTitle: "💈 Pankaj Hair Salon",
  todaysCollection: "Today's Collection",
  cash: "💵 Cash",
  upi: "📲 UPI",
  workerEarnings: "Worker Earnings",
  noActiveWorkersYet: "No active workers yet.",
  recentTransactions: "Recent Transactions",
  noTransactionsYetToday: "No transactions yet today.",
  viewAllTransactions: "View All Transactions →",
  addTransaction: "➕ Add Transaction",
  noServicesAvailable: "⚠️ No Services Available",
  noWorkersAvailable: "⚠️ No Workers Available",
  worker: "Worker",
  service: "Service",
  amount: "Amount",
  enterAmount: "Enter amount",
  paymentMode: "Payment Mode",
  cashLabel: "Cash",
  upiLabel: "UPI",
  saveTransaction: "✅ Save Transaction",
  back: "← Back",
  backToDashboard: "← Back to Dashboard",
  transactionsTitle: "📜 Transactions",

  expensesTitle: "💰 Expenses",
  todaysProfit: "Today's Profit",
  monthlyProfit: "Monthly Profit",
  expenseSummary: "Expense Summary",
  revenue: "Revenue",
  expenses: "Expenses",
  month: "This Month",
  addExpense: "Add Expense",
  category: "Category",
  noteOptional: "Note (optional)",
  saveExpense: "➕ Save Expense",
  expenseRecordNone: "No expenses recorded yet.",

  workerManagement: "👨 Worker Management",
  activeWorkers: "Active Workers",
  inactiveWorkers: "Inactive Workers",
  addNewWorker: "➕ Add New Worker",
  enterWorkerName: "Enter worker name",
  saveWorker: "Save Worker",
  workersList: "Workers List",
  noWorkersFound: "No workers found",
  addWorkerContinue: "Add a worker to continue",
  settledToday: "✅ Settled today",
  pendingSettlement: "⏳ Pending settlement",
  settle: "💰 Settle",
  paid: "Paid",
  deactivate: "🔴 Deactivate",
  reactivate: "🟢 Reactivate",
  noSettlementsYet: "No settlements yet",

  analyticsTitle: "📊 Analytics",
  thisWeekRevenue: "This Week — Revenue",
  avgPerDay: "📅 Avg Per Day",
  topWorker: "🏆 Top Worker",
  topService: "✂️ Top Service",
  last7Days: "Last 7 Days",
  noDataYet: "No data yet",

  reportsTitle: "📁 Reports",
  totalClosedDays: "Total Closed Days",
  totalRevenue: "Total Revenue",
  totalExpenses: "Total Expenses",
  noReportsYet: "No reports yet. Close a day to generate one.",
  closedAt: "Closed at",
  deleteReportTitle: "Delete Report",
  deleteReportConfirm: "Delete report for {{date}}?",

  cancel: "Cancel",
  deleteLabel: "Delete",
  confirm: "Confirm",

  editService: "✏️ Edit Service",
  addNewService: "➕ Add New Service",
  serviceName: "Service Name",
  price: "Price (₹)",
  saveLabel: "Save",
  update: "Update",
  serviceNameCannotBeEmpty: "Service name cannot be empty",
  priceMustBeValid: "Price must be greater than 0",
  error: "Error",
  success: "Success",
  duplicateServiceError: "A service with this name already exists",
  serviceAddedSuccess: "{{serviceName}} added successfully",
  serviceUpdatedSuccess: "{{serviceName}} updated successfully",
  cannotDeleteLastService:
    "At least one service must remain. Add a new service before deleting this one.",
  deleteService: "Delete Service",
  deleteServiceWarning: "Delete {{serviceName}}?",
  deleteServiceHistoricalWarning:
    "This service appears in historical reports. Deleting it will not affect existing reports, but it will be removed from future transactions.",
  serviceDeletedSuccess: "{{serviceName}} deleted successfully",

  deactivateWorkerTitle: "Deactivate Worker",
  deactivateWorkerConfirm:
    "Are you sure you want to deactivate {{workerName}}?",
  workerDeactivated: "{{workerName}} has been deactivated",
  alreadySettled: "Already Settled",
  alreadySettledMessage:
    "{{name}} is already settled today (₹{{amount}} at {{time}}).",
  noTransactions: "No Transactions",
  noTransactionsBeforeClosing:
    "Add at least one transaction before closing the day.",
  closeDay: "Close Day",
  closeDayConfirm:
    "Revenue: ₹{{totalCollection}}\nExpenses: ₹{{todayExpenseTotal}}\nProfit: ₹{{todayProfit}}\n\nCash: ₹{{cashTotal}}  UPI: ₹{{upiTotal}}\n\nClose the day?",
  settled: "Settled",
  payShare: "Pay ₹{{amount}}",
  settledSuccessfully: "{{name}} paid ₹{{amount}} ✅",
  invalidAmountTitle: "Invalid Amount",
  invalidAmountMessage: "Please enter a valid amount greater than 0",
  invalidExpenseAmount: "Please enter a valid expense amount.",
  expenseSavedSuccess: "Expense of ₹{{amount}} ({{category}}) saved ✅",
  deleteExpense: "Delete Expense",
  deleteExpenseConfirm: "Are you sure you want to delete this expense?",
  transactionHistory: "Transaction History",

  addServiceButton: "➕ Add New Service",
  servicesList: "Services List",
  noServicesFound: "No services found",
  addServiceToContinue: "Add a service to continue",
  edit: "✏️ Edit",
  deleteIconLabel: "🗑 Delete",
  infoNote: "ℹ️ Editing or deleting services won't affect historical reports.",
  goToWorkers: "Go to Workers",
  goToServices: "Go to Services",
  goBack: "← Back",
  goBackToDashboard: "← Back to Dashboard",
  noActiveWorkersFound: "No active workers found",
  pleaseAddWorkersFirst: "Please add workers in Workers section first",
  noServicesAvailableTitle: "No services available",
  pleaseAddServicesFirst: "Please add services in Services section first",
  savingsTitle: "Loading...",
  loading: "Loading...",
  placeholderServiceName: "e.g. Hair Spa",
  placeholderPrice: "e.g. 800",
  startNewDay: "🌅 Start New Day",
  saved: "Saved",
  expense: "Expense",
  expenseCategoryRent: "Rent",
  expenseCategoryElectricity: "Electricity",
  expenseCategoryProducts: "Products",
  expenseCategorySalary: "Salary",
  expenseCategoryMaintenance: "Maintenance",
  expenseCategoryWater: "Water",
  expenseCategoryInternet: "Internet",
  expenseCategoryTeaSnacks: "Tea & Snacks",
  expenseCategoryOther: "Other",
  expenseCategories: [
    "Rent",
    "Electricity",
    "Products",
    "Salary",
    "Maintenance",
    "Water",
    "Internet",
    "Tea & Snacks",
    "Other",
  ],
  homeBottomTabs: [
    { key: "home", label: "🏠 Home" },
    { key: "workers", label: "👨 Workers" },
    { key: "services", label: "✂️ Services" },
    { key: "reports", label: "📁 Reports" },
    { key: "analytics", label: "📊 Stats" },
    { key: "expenses", label: "💰 Expenses" },
  ],
  languageSwitcher: "Language",
  switchToEnglish: "Switch to English",
  switchToMarathi: "Switch to Marathi",
  projectTitle: "Project Pankaj",
  projectSubtitle: "Smart Salon Management System",
  projectFeatureTitle: "The application helps salon owners efficiently manage:",
  featureWorkers: "Workers",
  featureServices: "Services",
  featureTransactions: "Daily Transactions",
  featureExpenses: "Expenses",
  featureAttendance: "Attendance",
  featureSettlements: "Settlements",
  featureReports: "Reports",
  featureAnalytics: "Analytics",
  versionLabel: "Version",
  versionValue: "V9.1",
  platformLabel: "Platform",
  platformValue: "React Native + Expo SDK 54",
  architectureLabel: "Architecture",
  architectureValue: "Offline First",
  statusLabel: "Current Status",
  statusValue: "Production Ready",
  developerNameLabel: "Name",
  developerRoleLabel: "Role",
  developerCardSubtitle: "Professional Profile",
  developerName: "Ganesh Mulage and Team",
  developerRole: "Application developer",
  developerEmailLabel: "Work Email",
  developerEmail: "ganeshmulage31@gmail.com",
  developerMobileLabel: "Mobile",
  developerMobile: "+91 9623072057",
  footerDivider: "────────────────────────────",
  footerAppName: "Project Pankaj",
  footerMadeWith: "Made with ❤️ in Maharashtra, India",
  footerCraftedFor: "Crafted for Salon Professionals",
  footerCopyright: "© 2026 Ganesh Mulage",
  footerAllRights: "All Rights Reserved.",
};

export default en;
