const mr = {
  languageEnglish: "English",
  languageMarathi: "मराठी",
  switchLanguage: "भाषा बदला",
  moreTab: "अधिक",
  settingsTitle: "सेटिंग्ज",
  languageLabel: "भाषा",
  themeLabel: "थीम",
  themeSystem: "सिस्टम डीफॉल्ट",
  themeLight: "उजवा",
  themeDark: "गडद",
  aboutProject: "प्रोजेक्ट पंकज बद्दल",
  aboutProjectDescription:
    "हा सॅलून डॅशबोर्ड व्यवहार, कामगार, सेवा, खर्च आणि अहवाल एका ऍपमध्ये व्यवस्थापित करण्यात मदत करतो.",
  developerInfo: "विकसक माहिती",
  developerName: "पंकज यांनी विकसित",
  developerContact: "hello@pankajhairsalon.app",

  homeTab: "मुख्य",
  exploreTab: "शोधा",
  modalTitle: "मोडल",
  modalMessage: "हा एक मोडल आहे",
  goToHomeScreen: "मुख्य स्क्रीनवर या",

  salonTitle: "💈 पंकज हेअर सलून",
  todaysCollection: "आजचे एकूण",
  cash: "💵 रोकड",
  upi: "📲 UPI",
  workerEarnings: "कामगारांची कमाई",
  noActiveWorkersYet: "अभी तक कोई सक्रिय कार्यकर्ता नहीं है।",
  recentTransactions: "अलीकडील व्यवहार",
  noTransactionsYetToday: "आज अद्याप कोणतेही व्यवहार नाहीत.",
  viewAllTransactions: "सर्व व्यवहार पहा →",
  addTransaction: "➕ व्यवहार जोडा",
  noServicesAvailable: "⚠️ कोणत्याही सेवांचा उपलब्ध नाही",
  noWorkersAvailable: "⚠️ कोणत्याही कामगार नाहीत",
  worker: "कामगार",
  service: "सेवा",
  amount: "रक्कम",
  enterAmount: "रक्कम भरा",
  paymentMode: "पेमेंट मोड",
  cashLabel: "रोकड",
  upiLabel: "UPI",
  saveTransaction: "✅ व्यवहार जतन करा",
  back: "← परत",
  backToDashboard: "← डॅशबोर्डवर परत",
  transactionsTitle: "📜 व्यवहार",

  expensesTitle: "💰 खर्च",
  todaysProfit: "आजचा नफा",
  monthlyProfit: "मासिक नफा",
  expenseSummary: "खर्च सारांश",
  revenue: "उत्पन्न",
  expenses: "खर्च",
  month: "हा महिना",
  addExpense: "खर्च जोडा",
  category: "श्रेणी",
  noteOptional: "टीप (ऐच्छिक)",
  saveExpense: "➕ खर्च जतन करा",
  expenseRecordNone: "अद्याप कोणतेही खर्च नोंदलेले नाहीत.",

  workerManagement: "👨 कामगार व्यवस्थापन",
  activeWorkers: "सक्रिय कामगार",
  inactiveWorkers: "निष्क्रिय कामगार",
  addNewWorker: "➕ नवीन कामगार जोडा",
  enterWorkerName: "कामगाराचे नाव टाका",
  saveWorker: "कामगार जतन करा",
  workersList: "कामगारांची यादी",
  noWorkersFound: "कोणतेही कामगार सापडले नाहीत",
  addWorkerContinue: "सुरू करण्यासाठी कामगार जोडा",
  settledToday: "✅ आज ठरले",
  pendingSettlement: "⏳ न भरलेली रक्कम",
  settle: "💰 भरणा करा",
  paid: "भरणा केला",
  deactivate: "🔴 निष्क्रिय करा",
  reactivate: "🟢 पुन्हा सक्रिय करा",
  noSettlementsYet: "अद्याप कोणतीही ठराव नाही",

  analyticsTitle: "📊 विश्लेषण",
  thisWeekRevenue: "या आठवड्याचा महसूल",
  avgPerDay: "📅 प्रत्येकी दररोज",
  topWorker: "🏆 सर्वोत्तम कामगार",
  topService: "✂️ सर्वोत्तम सेवा",
  last7Days: "मागील 7 दिवस",
  noDataYet: "अद्याप डेटा नाही",

  reportsTitle: "📁 अहवाल",
  totalClosedDays: "बंद केलेले दिवस",
  totalRevenue: "एकूण महसूल",
  totalExpenses: "एकूण खर्च",
  noReportsYet: "अद्याप कोणतेही अहवाल नाहीत. एक दिवस बंद करा.",
  closedAt: "बंद केले वेळ",
  deleteReportTitle: "अहवाल हटवा",
  deleteReportConfirm: "{{date}} चा अहवाल हटवू?",

  cancel: "रद्द करा",
  deleteLabel: "हटवा",
  confirm: "पुष्टी करा",

  editService: "✏️ सेवा संपादित करा",
  addNewService: "➕ नवीन सेवा जोडा",
  serviceName: "सेवा नाव",
  price: "किंमत (₹)",
  saveLabel: "जतन करा",
  update: "अपडेट करा",
  serviceNameCannotBeEmpty: "सेवा नाव रिकामे असू नये",
  priceMustBeValid: "किंमत 0 पेक्षा जास्त असावी",
  error: "त्रुटी",
  success: "यश",
  duplicateServiceError: "या नावाची सेवा आधीच आहे",
  serviceAddedSuccess: "{{serviceName}} यशस्वीरित्या जोडले",
  serviceUpdatedSuccess: "{{serviceName}} यशस्वीरित्या अद्यतनित केले",
  cannotDeleteLastService:
    "किमान एक सेवा असणे आवश्यक आहे. हा हटवण्याआधी नवीन सेवा जोडा.",
  deleteService: "सेवा हटवा",
  deleteServiceWarning: "{{serviceName}} हटवू?",
  deleteServiceHistoricalWarning:
    "ही सेवा ऐतिहासिक अहवालात आहे. हटवल्याने विद्यमान अहवालांवर परिणाम होणार नाही, परंतु भविष्यातील व्यवहारांमधून काढले जाईल.",
  serviceDeletedSuccess: "{{serviceName}} यशस्वीरित्या हटवले",

  deactivateWorkerTitle: "कामगार निष्क्रिय करा",
  deactivateWorkerConfirm: "तुम्हाला {{workerName}} निष्क्रिय करायचे आहे का?",
  workerDeactivated: "{{workerName}} निष्क्रिय केले गेले",
  alreadySettled: "आधीच ठरले",
  alreadySettledMessage: "{{name}} आज आधीच ठरले आहे (₹{{amount}} at {{time}}).",
  noTransactions: "कोणतेही व्यवहार नाहीत",
  noTransactionsBeforeClosing: "दिवस बंद करण्यापूर्वी एक व्यवहार जोडा.",
  closeDay: "दिवस बंद करा",
  closeDayConfirm:
    "महसूल: ₹{{totalCollection}}\nखर्च: ₹{{todayExpenseTotal}}\nनफा: ₹{{todayProfit}}\n\nरोकड: ₹{{cashTotal}}  UPI: ₹{{upiTotal}}\n\nदिवस बंद करायचा?",
  settled: "ठरले",
  payShare: "₹{{amount}} भरा",
  settledSuccessfully: "{{name}} ने ₹{{amount}} भरले ✅",
  invalidAmountTitle: "अवैध रक्कम",
  invalidAmountMessage: "कृपया 0 पेक्षा जास्त वैध रक्कम भरा",
  invalidExpenseAmount: "कृपया वैध खर्च रक्कम भरा.",
  expenseSavedSuccess: "₹{{amount}} ({{category}}) खर्च जतन केले ✅",
  deleteExpense: "खर्च हटवा",
  deleteExpenseConfirm: "तुम्हाला हा खर्च हटवायचा आहे का?",
  transactionHistory: "व्यवहार इतिहास",

  addServiceButton: "➕ नवीन सेवा जोडा",
  servicesList: "सेवा यादी",
  noServicesFound: "कोणतीही सेवा सापडली नाही",
  addServiceToContinue: "सुरू करण्यासाठी सेवा जोडा",
  edit: "✏️ संपादित करा",
  deleteIconLabel: "🗑 हटवा",
  infoNote: "ℹ️ सेवांमध्ये बदल केल्याने ऐतिहासिक अहवालांवर परिणाम होत नाही.",
  goToWorkers: "कामगारांकडे जा",
  goToServices: "सेवांकडे जा",
  goBack: "← परत जा",
  goBackToDashboard: "← डॅशबोर्डवर परत",
  noActiveWorkersFound: "कोणतेही सक्रिय कामगार नाहीत",
  pleaseAddWorkersFirst: "कृपया प्रथम कामगार जोडा",
  noServicesAvailableTitle: "कोणतीही सेवा उपलब्ध नाही",
  pleaseAddServicesFirst: "कृपया प्रथम सेवांमध्ये जा",
  loading: "लोड करत आहे...",
  placeholderServiceName: "उदा. हेअर स्पा",
  placeholderPrice: "उदा. 800",
  startNewDay: "🌅 नवीन दिवस सुरू करा",
  saved: "जतन केले",
  expense: "खर्च",
  expenseCategoryRent: "भाडे",
  expenseCategoryElectricity: "विद्युत",
  expenseCategoryProducts: "उत्पादने",
  expenseCategorySalary: "पगार",
  expenseCategoryMaintenance: "देखभाल",
  expenseCategoryWater: "पाणी",
  expenseCategoryInternet: "इंटरनेट",
  expenseCategoryTeaSnacks: "चहा आणि स्नॅक्स",
  expenseCategoryOther: "इतर",
  expenseCategories: [
    "भाडे",
    "विद्युत",
    "उत्पादने",
    "पगार",
    "देखभाल",
    "पाणी",
    "इंटरनेट",
    "चहा आणि स्नॅक्स",
    "इतर",
  ],
  homeBottomTabs: [
    { key: "home", label: "🏠 मुख्य" },
    { key: "workers", label: "👨 कामगार" },
    { key: "services", label: "✂️ सेवा" },
    { key: "reports", label: "📁 अहवाल" },
    { key: "analytics", label: "📊 आकडे" },
    { key: "expenses", label: "💰 खर्च" },
  ],
  languageSwitcher: "भाषा",
  switchToEnglish: "English मध्ये बदला",
  switchToMarathi: "मराठीत बदला",
  projectTitle: "प्रोजेक्ट पंकज",
  projectSubtitle: "स्मार्ट सलून व्यवस्थापन प्रणाली",
  projectFeatureTitle:
    "हे अॅप सलून मालकांना कार्यक्षमतेने व्यवस्थापित करण्यात मदत करते:",
  featureWorkers: "कामगार",
  featureServices: "सेवा",
  featureTransactions: "दैनिक व्यवहार",
  featureExpenses: "खर्च",
  featureAttendance: "हजेरी",
  featureSettlements: "स्थापना",
  featureReports: "अहवाल",
  featureAnalytics: "विश्लेषण",
  versionLabel: "आवृत्ती",
  versionValue: "V9.1",
  platformLabel: "प्लॅटफॉर्म",
  platformValue: "React Native + Expo SDK 54",
  architectureLabel: "आर्किटेक्चर",
  architectureValue: "ऑफलाइन फर्स्ट",
  statusLabel: "सध्याची स्थिती",
  statusValue: "प्रोडक्शन रेडी",
  developerNameLabel: "नाव",
  developerRoleLabel: "भूमिका",
  developerCardSubtitle: "व्यावसायिक प्रोफाइल",
  developerRole: "अॅप्लिकेशन डेव्हलपर",
  developerEmailLabel: "वर्क ईमेल",
  developerEmail: "ganeshmulage31@gmail.com",
  developerMobileLabel: "मोबाइल",
  developerMobile: "+91 9623072057",
  footerDivider: "────────────────────────────",
  footerAppName: "प्रोजेक्ट पंकज",
  footerMadeWith: "महाराष्ट्र, भारतामध्ये ❤️ सह तयार केले",
  footerCraftedFor: "सलून व्यावसायिकांसाठी तयार केले",
  footerCopyright: "© 2026 गणेश मुलगे",
  footerAllRights: "सर्व हक्क राखीव आहेत.",
};

export default mr;
